/** Liste alphabétique des nationalités proposées dans les formulaires. */
export const NATIONALITIES = [
  'Afghane', 'Albanaise', 'Algérienne', 'Allemande', 'Andorrane', 'Angolaise',
  'Américaine', 'Antiguaise-et-Barbudienne', 'Argentine', 'Arménienne',
  'Australienne', 'Autrichienne', 'Azerbaïdjanaise', 'Bahaméenne', 'Bahreïnienne',
  'Bangladaise', 'Barbadienne', 'Belge', 'Bélizienne', 'Béninoise',
  'Bhoutanaise', 'Biélorusse', 'Birmane', 'Bolivienne', 'Bosniaque',
  'Botswanaise', 'Brésilienne', 'Brunéienne', 'Bulgare', 'Burkinabè',
  'Britannique', 'Burundaise', 'Cambodgienne', 'Camerounaise', 'Canadienne',
  'Cap-Verdienne', 'Centrafricaine', 'Chilienne', 'Chinoise', 'Chypriote',
  'Colombienne', 'Comorienne', 'Congolaise (République du Congo)',
  'Congolaise (République démocratique du Congo)', 'Costaricienne', 'Croate',
  'Cubaine', 'Danoise', 'Djiboutienne', 'Dominicaine (Dominique)',
  'Dominicaine (République dominicaine)', 'Égyptienne', 'Émirienne',
  'Équato-Guinéenne', 'Équatorienne', 'Érythréenne', 'Espagnole', 'Estonienne',
  'Eswatinienne', 'Éthiopienne', 'Fidjienne', 'Finlandaise', 'Française',
  'Gabonaise', 'Gambienne', 'Géorgienne', 'Ghanéenne', 'Grenadienne',
  'Grecque', 'Guatémaltèque', 'Guinéenne', 'Bissau-Guinéenne', 'Guyanienne',
  'Haïtienne', 'Hondurienne', 'Hongroise', 'Indienne', 'Indonésienne',
  'Irakienne', 'Iranienne', 'Irlandaise', 'Islandaise', 'Israélienne',
  'Italienne', 'Jamaïcaine', 'Japonaise', 'Jordanienne', 'Kazakhstanaise',
  'Kényane', 'Kirghize', 'Kiribatienne', 'Kittitienne-et-Névicienne',
  'Koweïtienne', 'Laotienne', 'Lesothane', 'Lettonne', 'Libanaise',
  'Libérienne', 'Libyenne', 'Liechtensteinoise', 'Lituanienne',
  'Luxembourgeoise', 'Macédonienne (Macédoine du Nord)', 'Malgache',
  'Malaisienne', 'Malawite', 'Maldivienne', 'Malienne', 'Maltaise',
  'Marocaine', 'Marshallienne', 'Mauricienne', 'Mauritanienne', 'Mexicaine',
  'Micronésienne', 'Moldave', 'Monégasque', 'Mongole', 'Monténégrine',
  'Mozambicaine', 'Namibienne', 'Nauruane', 'Néerlandaise', 'Néo-Zélandaise',
  'Népalaise', 'Nicaraguayenne', 'Nigériane', 'Nigérienne', 'Nord-Coréenne',
  'Norvégienne',
  'Ougandaise', 'Omanaise', 'Ouzbèke', 'Pakistanaise', 'Palaosienne',
  'Palestinienne', 'Panaméenne', 'Papouasienne-Néo-Guinéenne', 'Paraguayenne',
  'Péruvienne', 'Philippine', 'Polonaise', 'Portugaise', 'Qatarienne',
  'Kosovare', 'Roumaine', 'Russe', 'Rwandaise', 'Sahraouie', 'Sainte-Lucienne',
  'Saint-Marinaise', 'Saint-Vincentaise-et-Grenadine', 'Salomonaise',
  'Salvadorienne', 'Samoane', 'Santoméenne', 'Saoudienne', 'Sénégalaise',
  'Serbe', 'Seychelloise', 'Sierra-Léonaise', 'Singapourienne', 'Slovaque',
  'Slovène', 'Somalienne', 'Soudanaise', 'Sri-Lankaise', 'Sud-Africaine',
  'Sud-Coréenne', 'Sud-Soudanaise', 'Suédoise', 'Suissesse', 'Surinamaise',
  'Syrienne', 'Tadjike', 'Taïwanaise', 'Tanzanienne', 'Tchadienne', 'Tchèque',
  'Thaïlandaise', 'Timoraise', 'Togolaise', 'Tongienne', 'Trinidadienne',
  'Tunisienne', 'Turkmène', 'Turque', 'Tuvaluane', 'Ukrainienne', 'Uruguayenne',
  'Vanuatuane', 'Vaticane', 'Vénézuélienne', 'Vietnamienne', 'Yéménite',
  'Zambienne', 'Zimbabwéenne', 'Autre',
]
